"""Domain models for update planning."""

from __future__ import annotations

from enum import Enum
from pydantic import BaseModel, ConfigDict, Field


class ActionType(str, Enum):
    UPDATE = "Update"
    SKIP = "Skip"
    DELETE = "Delete"


class SectionDecision(BaseModel):
    """AI-generated decision for an individual section based on Content Intelligence.

    The planner maps the overarching article intelligence into granular,
    prescriptive directives for the generator.
    """

    model_config = ConfigDict(extra="forbid")

    section_id: str | None = Field(default=None, description="Unique data-astra-id of the section.")
    section: str = Field(min_length=1, description="Section name (must match a detected section).")
    action: ActionType = Field(description="Update, Skip, or Delete.")
    reason: str = Field(min_length=1, description="Why the AI chose this action.")
    confidence: float = Field(ge=0.0, le=1.0, description="Confidence score (0.0 to 1.0).")
    
    # Prescriptive fields for the generator
    fields_to_update: list[str] = Field(
        default_factory=list, description="Specific elements that must be updated."
    )
    fields_to_preserve: list[str] = Field(
        default_factory=list, description="Specific elements that must remain exactly the same."
    )
    forbidden_changes: list[str] = Field(
        default_factory=list, description="Actions the generator is absolutely forbidden to take."
    )
    required_entities: list[str] = Field(
        default_factory=list, description="Entities or keywords that must be present in the output."
    )
    expected_output: str = Field(
        default="", description="A brief description of what the final updated section should look like."
    )


# Maintain backward compatibility for modules importing UpdateAction if needed
UpdateAction = SectionDecision


class UpdatePlan(BaseModel):
    """The complete content update plan generated by the AI Planner."""
    
    model_config = ConfigDict(extra="forbid")

    new_title: str | None = Field(
        default=None,
        description="Optional new title for the WordPress post.",
    )
    custom_instructions: str | None = Field(
        default=None,
        description="Optional custom instructions injected during analysis.",
    )
    actions: list[SectionDecision] = Field(
        default_factory=list,
        description="List of prescriptive actions to perform on the article.",
    )


class UpdateReport(BaseModel):
    """Telemetry and reporting for the HTML Update Engine."""

    updated_sections: list[str] = Field(
        default_factory=list, description="Sections successfully updated."
    )
    skipped_sections: list[str] = Field(
        default_factory=list, description="Sections skipped or ignored."
    )
    confidence_score: float = Field(
        default=0.0, description="Average confidence of applied updates."
    )
    section_confidences: dict[str, float] = Field(
        default_factory=dict, description="Confidence score for every updated section."
    )
    warnings: list[str] = Field(
        default_factory=list, description="Warnings encountered during generation."
    )
    diagnostics: dict[str, str] = Field(
        default_factory=dict, description="Structured diagnostics mapping section name to reason skipped."
    )
    processing_time_seconds: float = Field(
        default=0.0, description="Time taken to run the update engine."
    )
